# Integração Python + Excel

### 2 formas:

1. Pandas
    - Mais usada no geral
    - Trata o Excel como uma base de dados
    - Faz o que quiser com o arquivo
    - Pode desfazer a estrutura original do arquivo, caso queira editar
    
2. Openpyxl
    - Trata o Excel como uma planilha mesmo que pode ter várias coisas
    - Edita "como se fosse um VBA"
    - Menos eficiente
    - Mantém mais a estrutura original do arquivo, mas cuidado porque não necessariamente tudo, então tem que testar

### Desafio

- Temos uma planilha de produtos e serviços. Com o aumento de imposto sobre os serviços, temos que atualizar o preço dos produtos impactados pela mudança.

Novo Multiplicador Imposto: 1.5

In [1]:
# pandas
import pandas as pd

tabela = pd.read_excel("Produtos.xlsx")
display(tabela)

,Produtos,Preço Base Original,Tipo,Multiplicador Imposto,Preço Base Reais
0,Tablet,999.99,Produto,1.1,1099.989
1,Pós Graduação,4500.00,Serviço,1.3,5850.000
2,Celular,899.99,Produto,1.1,989.989
3,Passagem Aérea,799.00,Serviço,1.3,1038.700
4,Computador,3000.00,Produto,1.1,3300.000
5,SPA,480.48,Serviço,1.3,624.624
6,Corte Cabelo,50.00,Serviço,1.3,65.000

In [6]:
# atualizando a cotação e as colunas seguintes
tabela.loc[tabela['Tipo']=='Serviço', 'Multiplicador Imposto'] = 1.5
display(tabela)

#tabela a conta do preço base reais
tabela["Preço Base Reais"] = tabela['Multiplicador Imposto'] * tabela['Preço Base Original']

tabela.to_excel('ProdutosPandas.xlsx')

,Produtos,Preço Base Original,Tipo,Multiplicador Imposto,Preço Base Reais
0,Tablet,999.99,Produto,1.1,1099.989
1,Pós Graduação,4500.00,Serviço,1.5,5850.000
2,Celular,899.99,Produto,1.1,989.989
3,Passagem Aérea,799.00,Serviço,1.5,1038.700
4,Computador,3000.00,Produto,1.1,3300.000
5,SPA,480.48,Serviço,1.5,624.624
6,Corte Cabelo,50.00,Serviço,1.5,65.000

In [11]:
# openpyxl
from openpyxl import Workbook, load_workbook

planilha = load_workbook('Produtos.xlsx')

aba_ativa = planilha.active

for celula in aba_ativa['C']:
    if celula.value == 'Serviço':
        linha = celula.row
        aba_ativa[f'D{linha}'] = 1.5

planilha.save("ProdutosOpenPy.xlsx")